#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 29 21:10:13 2020

@author: nancyscarlet
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('Position_Salaries.csv')
X= dataset.iloc[:,1].values
y=dataset.iloc[:,2].values

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(X.reshape(-1,1),y.reshape(-1,1))
y_pred = regressor.predict(np.array(7.5).reshape(-1,1))
X_grid = np.arange(min(X),max(X),step=0.01)
X_grid = X_grid.reshape(len(X_grid),1)
plt.scatter(X,y,color='red')
plt.plot(X_grid,regressor.predict(X_grid),color='blue')
plt.title('Decision tree regression')
plt.xlabel('Position')
plt.ylabel('Salary')
plt.show()